name: Deploy GitHub Pages - WIP and MAIN

on:
  push:
    branches:
      - main
      - wip
  workflow_dispatch: # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Clone the existing gh-pages branch
      - name: Clone gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          mkdir -p gh-pages/public

      # Step 3: Copy build output to the appropriate directory
      - name: Prepare deployment
        run: |
          echo "gh-pages before Building site for branch: $GITHUB_REF_NAME"
          ls -lR
          if [ "$GITHUB_REF_NAME" == "main" ]; then
            echo MAIN
            mkdir -p gh-pages/public/stable
            find . -maxdepth 1 -type f -exec cp {} gh-pages/public/stable/ \;  # Copy only files
          elif [ "$GITHUB_REF_NAME" == "wip" ]; then
            echo WIP
            mkdir -p gh-pages/public/wip
            find . -maxdepth 1 -type f -exec cp {} gh-pages/public/wip/ \;  # Copy only files
          else
            echo NONE
          fi
          echo "gh-pages after Building site for branch: $GITHUB_REF_NAME"
          ls -lR

      # Step 4: Commit and push changes
      - name: Commit and push
        run: |
          cd gh-pages
          git add .
          git commit -m "Update GitHub Pages for $GITHUB_REF_NAME"
          git push origin gh-pages
