name: Deploy Stable or WIP GitHub Pages

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - wip
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the site (replace this with your build process if needed)
      - name: Build site
        run: |
          echo "Building site for branch $GITHUB_REF_NAME"
          if [ "$GITHUB_REF_NAME" == "main" ]; then
            echo "-------------------- b main ---------------"
            ls -lR
            echo "-------------------- b main ---------------"
            mkdir -p public/stable
            find . -maxdepth 1 -type f -exec cp {} public/stable/ \;  # Copy only files
            echo "-------------------- a ---------------"
            ls -lR
            echo "-------------------- a ---------------"
          elif [ "$GITHUB_REF_NAME" == "wip" ]; then
            echo "-------------------- b wip ---------------"
            ls -lR
            echo "-------------------- b wip ---------------"
            mkdir -p public/wip
            find . -maxdepth 1 -type f -exec cp {} public/wip/ \;  # Copy only files
            echo "-------------------- a wip ---------------"
            ls -lR
            echo "-------------------- a wip ---------------"
          fi          

      # Deploy to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
          force_orphan: true
          keep_files: true
