name: Deploy Stable or WIP GitHub Pages

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - wip
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build the site (replace this with your build process if needed)
      - name: Build site
        run: |
          echo "Building site for branch $GITHUB_REF_NAME"
          if [ "$GITHUB_REF_NAME" == "main" ]; then
            mkdir -p public/stable
            cp * public/stable
          elif [ "$GITHUB_REF_NAME" == "wip" ]; then
            mkdir -p public/wip
            cp * public/wip
          fi

      # Deploy to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true
